# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # 환경 변수 파일 생성
      # echo명령어 : 콘솔 창에 인수로 받은 문자열 출력하는 명령어, >>를 사용하면 .env 파일에 저장
  
    - name:  Create .env file
      uses: skiddph/actions-env@v1.0.3
      with:
        file: .env
        prefix: 'VITE_'
      env:
        KAKAO_MAP_JS_KEY: ${{secrets.KAKAO_MAP_JS_KEY}}
        KAKAO_REST_API_KEY: ${{secrets.KAKAO_REST_API_KEY}}
        KAKAO_REDIRECT_URI: ${{secrets.KAKAO_REDIRECT_URI}}
        TRAVELMAKER_API_URL: ${{secrets.TRAVELMAKER_API_URL}}
        run: |
          echo "KAKAO_MAP_JS_KEY : $KAKAO_MAP_JS_KEY"
          echo "KAKAO_REST_API_KEY : $KAKAO_REST_API_KEY"
          echo "KAKAO_REDIRECT_URI : $KAKAO_REDIRECT_URI"
          echo "TRAVELMAKER_API_URL : $TRAVELMAKER_API_URL"
          echo "KAKAO_MAP_JS_KEY : ${{secrets.KAKAO_MAP_JS_KEY}}"
          echo "KAKAO_REST_API_KEY : ${{secrets.KAKAO_REST_API_KEY}}"
          echo "KAKAO_REDIRECT_URI : ${{secrets.KAKAO_REDIRECT_URI}}"
          echo "TRAVELMAKER_API_URL : ${{secrets.TRAVELMAKER_API_URL}}"
    
    - uses: actions/checkout@v3
    # 해당 프로젝트에서 사용할 라이브러리 설치
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm i
    - run: npm run build --if-present

    - uses: awact/s3-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        SOURCE_DIR: './dist'
        AWS_REGION: ${{ secrets.AWS_BUCKET_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}